# ABOUTME: Generated model-to-display-name mapping.
# ABOUTME: Auto-generated by scripts/generate_icons.py — do not edit by hand.

MODEL_NAMES = {
    "mk4": "Prusa MK4S",
    "mk3": "Prusa MK3S+",
    "mini": "Prusa MINI+",
    "core_one": "Prusa Core One+",
    "core_one_l": "Prusa Core One L",
    "xl": "Prusa XL",
    "v2.4": "Voron 2.4",
    "trident": "Voron Trident",
    "v0": "Voron 0.2r1",
    "positron": "Positron V3.2",
    "p1s": "Bambu Lab P1S",
    "micron": "Micron",
}
