# ABOUTME: Converts PNG images to 1-bit 32x32 Rez ICON resource definitions.
# ABOUTME: Reads from assets/icons/, writes resources/PrintWatchIcons.r.

import argparse
import sys
from pathlib import Path
from PIL import Image

ICON_SIZE = 32
ICON_BYTES = (ICON_SIZE * ICON_SIZE) // 8  # 128 bytes

ICON_MAP = {
    "generic":   200,
    "mk4":       201,
    "mk3":       202,
    "mini":      203,
    "core_one":  204,
    "xl":        205,
    "v2_4":      206,
    "trident":   207,
    "k1":        208,
    "ender":     209,
    "bambu":     210,
}

ICON_NAMES = {
    200: "Generic 3D Printer",
    201: "Prusa MK4",
    202: "Prusa MK3S+",
    203: "Prusa MINI+",
    204: "Prusa Core One",
    205: "Prusa XL",
    206: "Voron 2.4",
    207: "Voron Trident",
    208: "Creality K1",
    209: "Creality Ender 3",
    210: "Bambu Lab",
}


def png_to_icon_bytes(path: Path, threshold: bool = False) -> bytes:
    """Convert a PNG to 128 bytes of 1-bit bitmap data (32x32)."""
    img = Image.open(path).convert("L").resize(
        (ICON_SIZE, ICON_SIZE), Image.LANCZOS
    )
    if threshold:
        bw = img.point(lambda x: 0 if x < 128 else 255, "1")
    else:
        bw = img.convert("1")

    pixels = list(bw.get_flattened_data())
    result = bytearray(ICON_BYTES)
    for row in range(ICON_SIZE):
        for col in range(ICON_SIZE):
            pixel = pixels[row * ICON_SIZE + col]
            if pixel == 0:
                byte_idx = row * 4 + col // 8
                bit_idx = 7 - (col % 8)
                result[byte_idx] |= (1 << bit_idx)
    return bytes(result)


def format_hex_lines(data: bytes, bytes_per_line: int = 16) -> list[str]:
    """Format raw bytes as Rez hex string lines."""
    lines = []
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i:i + bytes_per_line]
        pairs = " ".join(
            f"{chunk[j]:02X}{chunk[j+1]:02X}" for j in range(0, len(chunk), 2)
        )
        lines.append(f'    $"{pairs}"')
    return lines


def generate_rez(icons: dict[int, bytes]) -> str:
    """Generate a complete Rez source file from icon data."""
    parts = [
        "/* ABOUTME: Generated 32x32 1-bit printer model icons. */",
        "/* ABOUTME: Auto-generated by scripts/generate_icons.py — do not edit by hand. */",
        "",
    ]
    for res_id in sorted(icons.keys()):
        name = ICON_NAMES.get(res_id, "Unknown")
        hex_lines = format_hex_lines(icons[res_id])
        parts.append(f'data \'ICON\' ({res_id}, "{name}") {{')
        parts.extend(hex_lines)
        parts.append("};")
        parts.append("")
    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(
        description="Convert PNG icons to Rez ICON resources"
    )
    parser.add_argument(
        "--input", default="assets/icons",
        help="Directory containing source PNGs (default: assets/icons)"
    )
    parser.add_argument(
        "--output", default="resources/PrintWatchIcons.r",
        help="Output Rez file (default: resources/PrintWatchIcons.r)"
    )
    parser.add_argument(
        "--threshold", action="store_true",
        help="Use threshold instead of Floyd-Steinberg dithering"
    )
    args = parser.parse_args()

    input_dir = Path(args.input)
    if not input_dir.is_dir():
        print(f"Input directory not found: {input_dir}", file=sys.stderr)
        sys.exit(1)

    icons = {}
    for stem, res_id in ICON_MAP.items():
        png_path = input_dir / f"{stem}.png"
        if png_path.exists():
            icons[res_id] = png_to_icon_bytes(png_path, args.threshold)
            print(f"  {stem}.png -> ICON {res_id} ({ICON_NAMES[res_id]})")
        else:
            print(f"  {stem}.png not found, skipping ICON {res_id}")

    if not icons:
        print("No icons found. Place PNGs in assets/icons/.", file=sys.stderr)
        sys.exit(1)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate_rez(icons))
    print(f"\nWrote {len(icons)} icon(s) to {output_path}")


if __name__ == "__main__":
    main()
