# ABOUTME: Converts PNG images to 1-bit Rez resources for the classic Mac client.
# ABOUTME: Reads model config from assets/icons/models.yaml, generates Rez and C sources.

import argparse
import math
import sys
from pathlib import Path
from PIL import Image, ImageDraw
import yaml

MAX_HEIGHT = 200


def load_models(models_path: Path) -> list[dict]:
    with open(models_path) as f:
        data = yaml.safe_load(f)
    return data["models"]


def png_to_bitmap(path: Path) -> tuple[int, int, int, bytes]:
    """Convert a PNG to 1-bit bitmap data, scaled to fit MAX_HEIGHT.

    Returns (width, height, rowBytes, bitmap_data).
    """
    img = Image.open(path).convert("L")
    w, h = img.size

    if h > MAX_HEIGHT:
        scale = MAX_HEIGHT / h
        w = int(w * scale)
        h = MAX_HEIGHT
        img = img.resize((w, h), Image.LANCZOS)

    bw = img.point(lambda x: 0 if x < 128 else 255, "1")

    row_bytes = ((w + 15) // 16) * 2
    pixels = list(bw.get_flattened_data())
    result = bytearray(row_bytes * h)

    for row in range(h):
        for col in range(w):
            if pixels[row * w + col] == 0:
                byte_idx = row * row_bytes + col // 8
                bit_idx = 7 - (col % 8)
                result[byte_idx] |= (1 << bit_idx)

    return w, h, row_bytes, bytes(result)


def format_hex_lines(data: bytes, bytes_per_line: int = 16) -> list[str]:
    """Format raw bytes as Rez hex string lines."""
    lines = []
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i:i + bytes_per_line]
        if len(chunk) % 2 != 0:
            chunk = chunk + b'\x00'
        pairs = " ".join(
            f"{chunk[j]:02X}{chunk[j+1]:02X}" for j in range(0, len(chunk), 2)
        )
        lines.append(f'    $"{pairs}"')
    return lines


def generate_preview(models: list[dict],
                     bitmaps: dict[int, tuple[int, int, int, bytes]],
                     path: str, scale: int = 2):
    """Render all icons into a single preview PNG."""
    names = {m["id"]: m["name"] for m in models}
    pad = 10
    total_w = 0
    max_h = 0
    for res_id in sorted(bitmaps.keys()):
        w, h, _, _ = bitmaps[res_id]
        total_w += w * scale + pad
        max_h = max(max_h, h * scale)

    img = Image.new("1", (total_w + pad, max_h + 30 * scale), 1)
    draw = ImageDraw.Draw(img)

    x0 = pad
    for res_id in sorted(bitmaps.keys()):
        w, h, row_bytes, data = bitmaps[res_id]
        for py in range(h):
            for px in range(w):
                byte_idx = py * row_bytes + px // 8
                bit_idx = 7 - (px % 8)
                if data[byte_idx] & (1 << bit_idx):
                    sx, sy = x0 + px * scale, pad + py * scale
                    draw.rectangle(
                        [sx, sy, sx + scale - 1, sy + scale - 1], fill=0
                    )
        label = names.get(res_id, str(res_id))
        draw.text((x0, pad + h * scale + 4), label, fill=0)
        x0 += w * scale + pad

    img.save(path)
    print(f"Preview saved to {path}")


def generate_rez(models: list[dict],
                 bitmaps: dict[int, tuple[int, int, int, bytes]]) -> str:
    """Generate Rez source with PIMG resources (width, height, rowBytes + bitmap)."""
    names = {m["id"]: m["name"] for m in models}
    parts = [
        "/* ABOUTME: Generated 1-bit printer model images. */",
        "/* ABOUTME: Auto-generated by scripts/generate_icons.py — do not edit by hand. */",
        "",
    ]
    for res_id in sorted(bitmaps.keys()):
        name = names.get(res_id, "Unknown")
        w, h, row_bytes, data = bitmaps[res_id]
        header = (
            w.to_bytes(2, "big")
            + h.to_bytes(2, "big")
            + row_bytes.to_bytes(2, "big")
        )
        hex_lines = format_hex_lines(header + data)
        parts.append(f'data \'PIMG\' ({res_id}, "{name}") {{')
        parts.extend(hex_lines)
        parts.append("};")
        parts.append("")
    return "\n".join(parts)


def generate_c_mapping(models: list[dict]) -> str:
    """Generate the C icon mapping table as an includable .inc file."""
    fallback_id = None
    entries = []

    for m in models:
        if "match" not in m:
            fallback_id = m["id"]
            continue
        entries.append(
            f'    {{ "{m["match"]}", {m["id"]} }}'
        )

    all_ids = [m["id"] for m in models]
    lines = [
        "/* ABOUTME: Generated icon mapping table. */",
        "/* ABOUTME: Auto-generated by scripts/generate_icons.py — do not edit by hand. */",
        "",
        "static const IconMapping kIconMap[] = {",
    ]
    lines.append(",\n".join(entries) + ",")
    lines.append("    { NULL, 0 }")
    lines.append("};")
    lines.append("")
    lines.append(f"#define kGenericIconID {fallback_id}")
    lines.append(f"#define kFirstIconID   {min(all_ids)}")
    lines.append(f"#define kLastIconID    {max(all_ids)}")
    lines.append("")
    return "\n".join(lines)


def generate_python_mapping(models: list[dict]) -> str:
    """Generate a Python dict mapping model match strings to display names."""
    lines = [
        "# ABOUTME: Generated model-to-display-name mapping.",
        "# ABOUTME: Auto-generated by scripts/generate_icons.py — do not edit by hand.",
        "",
        "MODEL_NAMES = {",
    ]
    for m in models:
        if "match" in m:
            lines.append(f'    "{m["match"]}": "{m["name"]}",')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Convert PNG icons to Rez PIMG resources"
    )
    parser.add_argument(
        "--input", default="assets/icons",
        help="Directory containing source PNGs and models.yaml (default: assets/icons)"
    )
    parser.add_argument(
        "--output", default="resources/PrintWatchIcons.r",
        help="Output Rez file (default: resources/PrintWatchIcons.r)"
    )
    parser.add_argument(
        "--c-output", default="src/icon_map.inc",
        help="Output C mapping table (default: src/icon_map.inc)"
    )
    parser.add_argument(
        "--py-output", default="proxy/model_names.py",
        help="Output Python name mapping (default: proxy/model_names.py)"
    )
    parser.add_argument(
        "--preview", default=None,
        help="Output a scaled-up preview PNG grid (e.g. --preview preview.png)"
    )
    args = parser.parse_args()

    input_dir = Path(args.input)
    models_path = input_dir / "models.yaml"
    if not models_path.exists():
        print(f"Model config not found: {models_path}", file=sys.stderr)
        sys.exit(1)

    models = load_models(models_path)

    bitmaps = {}
    for m in models:
        png_path = input_dir / f"{m['file']}.png"
        if png_path.exists():
            w, h, rb, data = png_to_bitmap(png_path)
            bitmaps[m["id"]] = (w, h, rb, data)
            print(f"  {m['file']}.png -> PIMG {m['id']} ({w}x{h}, {len(data)+6}B)")
        else:
            print(f"  {m['file']}.png not found, skipping PIMG {m['id']}")

    if not bitmaps:
        print("No icons found. Place PNGs in assets/icons/.", file=sys.stderr)
        sys.exit(1)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate_rez(models, bitmaps))
    print(f"\nWrote {len(bitmaps)} image(s) to {output_path}")

    c_output_path = Path(args.c_output)
    c_output_path.parent.mkdir(parents=True, exist_ok=True)
    c_output_path.write_text(generate_c_mapping(models))
    print(f"Wrote C mapping table to {c_output_path}")

    py_output_path = Path(args.py_output)
    py_output_path.parent.mkdir(parents=True, exist_ok=True)
    py_output_path.write_text(generate_python_mapping(models))
    print(f"Wrote Python name mapping to {py_output_path}")

    if args.preview:
        generate_preview(models, bitmaps, args.preview)


if __name__ == "__main__":
    main()
