#!/bin/bash
# One-time project setup: fetch dependencies, build the Retro68 toolchain,
# and verify the install. Equivalent to running the three sub-scripts in
# sequence; safe to re-run because each sub-script is itself idempotent.
#
# Usage: ./scripts/setup.sh

set -e

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

section() {
    echo
    echo "================================================================"
    echo "  $1"
    echo "================================================================"
}

section "1/4  Installing Homebrew prerequisites"
if ! command -v brew >/dev/null 2>&1; then
    cat >&2 <<EOF
Homebrew is not installed.

Install it with:
  /bin/bash -c "\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

Then re-run scripts/setup.sh.
EOF
    exit 1
fi
# brew bundle is a no-op for formulae that are already installed, so
# re-running setup.sh is cheap. Edit ./Brewfile to add deps.
brew bundle install --file="$PROJECT_ROOT/Brewfile"

section "2/4  Fetching dependencies"
"$PROJECT_ROOT/scripts/fetch-deps.sh"

section "3/5  Building Retro68 toolchain"
"$PROJECT_ROOT/scripts/build-retro68.sh"

section "4/5  Generating ~/.LaunchAPPL.cfg"
MINIVMAC_DIR="$PROJECT_ROOT/deps/minivmac"
LAUNCHAPPL_CFG="$HOME/.LaunchAPPL.cfg"

if [ -f "$LAUNCHAPPL_CFG" ]; then
    echo "==> $LAUNCHAPPL_CFG already exists — skipping"
elif [ -d "$MINIVMAC_DIR/minivmac-macOS-SEFDHD.app" ] \
  && [ -f "$MINIVMAC_DIR/SEFDHD.ROM" ] \
  && [ -f "$MINIVMAC_DIR/autoquit-1.1.1.dsk" ] \
  && [ -f "$MINIVMAC_DIR/autquit7-1.4.1.dsk" ]; then
    # Pick the best available system image (prefer System 7).
    if [ -f "$MINIVMAC_DIR/System7_0_1.img" ]; then
        SYS_IMAGE="./System7_0_1.img"
    elif [ -f "$MINIVMAC_DIR/disk1.dsk" ]; then
        SYS_IMAGE="./disk1.dsk"
    else
        echo "==> No system image found — skipping LaunchAPPL config"
        echo "   (re-run 'make setup' after deps are in place)"
        SYS_IMAGE=""
    fi
    if [ -n "$SYS_IMAGE" ]; then
        cat > "$LAUNCHAPPL_CFG" <<EOF
# Generated by VibeRetro68 setup — edit freely.
# To switch system versions, change system-image:
#   System 6.0.8:  system-image = ./disk1.dsk
#   System 7.0.1:  system-image = ./System7_0_1.img
# LaunchAPPL picks the matching autoquit variant automatically.
emulator = minivmac
minivmac-dir = $MINIVMAC_DIR
minivmac-path = ./minivmac-macOS-SEFDHD.app
minivmac-rom = ./SEFDHD.ROM
system-image = $SYS_IMAGE
autoquit-image = ./autoquit-1.1.1.dsk
autquit7-image = ./autquit7-1.4.1.dsk
EOF
        echo "==> Wrote $LAUNCHAPPL_CFG (using $SYS_IMAGE)"
    fi
else
    echo "==> Mini vMac files incomplete — skipping LaunchAPPL config"
    echo "   (re-run 'make setup' after deps are in place)"
fi

section "5/5  Running doctor"
"$PROJECT_ROOT/scripts/doctor.sh"
